# Generated by Django 5.1.1 on 2024-10-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("school_name", models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=99)),
                ("is_open", models.BooleanField()),
                ("is_tabulated", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="JournalScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.IntegerField()),
                ("field2", models.IntegerField()),
                ("field3", models.IntegerField()),
                ("field4", models.IntegerField()),
                ("field5", models.IntegerField()),
                ("field6", models.IntegerField()),
                ("field7", models.IntegerField()),
                ("field8", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("contestid", models.IntegerField()),
                ("presentation", models.BooleanField()),
                ("mdo", models.BooleanField()),
                ("journal", models.BooleanField()),
                ("penalties", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="JudgeClusters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MachineDesignScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.IntegerField()),
                ("field2", models.IntegerField()),
                ("field3", models.IntegerField()),
                ("field4", models.IntegerField()),
                ("field5", models.IntegerField()),
                ("field6", models.IntegerField()),
                ("field7", models.IntegerField()),
                ("field8", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapClusterToTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clusterid", models.IntegerField()),
                ("teamid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapCoachToTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamid", models.IntegerField()),
                ("coachid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapContestToJudge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contestid", models.IntegerField()),
                ("judegeid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapContestToOrganizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contestid", models.IntegerField()),
                ("organizerid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapContestToTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contestid", models.IntegerField()),
                ("teamid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapJudgeToCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judegeid", models.IntegerField()),
                ("clusterid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapJudgeToJournalScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judgeid", models.IntegerField()),
                ("scoresheetid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapJudgeToMachineDesignScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judgeid", models.IntegerField()),
                ("scoresheetid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapJudgeToPresentationScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judgeid", models.IntegerField()),
                ("scoresheetid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapTeamToJournalScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamid", models.IntegerField()),
                ("scoresheetid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapTeamToMachineDesignScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamid", models.IntegerField()),
                ("scoresheetid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapTeamToPenalties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamid", models.IntegerField()),
                ("scoresheetid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapTeamToPresentationScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamid", models.IntegerField()),
                ("scoresheetid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapUserToRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (1, "Admin"),
                            (2, "Organizer"),
                            (3, "Judge"),
                            (4, "Coach"),
                        ]
                    ),
                ),
                ("uuid", models.IntegerField()),
                ("relatedid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Penalties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PresentationPenalties", models.IntegerField()),
                ("MachinePenalties", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PresentationScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.IntegerField()),
                ("field2", models.IntegerField()),
                ("field3", models.IntegerField()),
                ("field4", models.IntegerField()),
                ("field5", models.IntegerField()),
                ("field6", models.IntegerField()),
                ("field7", models.IntegerField()),
                ("field8", models.IntegerField()),
                ("penalty", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=99)),
                ("journal_score", models.FloatField()),
                ("presentation_score", models.FloatField()),
                ("machinedesign_score", models.FloatField()),
                ("score_penalties", models.FloatField()),
                ("judge_cluster", models.IntegerField()),
            ],
        ),
    ]
