# Generated by Django 5.1.1 on 2024-10-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emdcbackend", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Teams", new_name="Team",),
    ]
