# Generated by Django 4.2.16 on 2024-10-30 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MapScoresheetToTeamJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.IntegerField()),
                ('judgeid', models.IntegerField()),
                ('scoresheetid', models.IntegerField()),
                ('sheetType', models.IntegerField(choices=[(1, 'Presentation'), (2, 'Journal'), (3, 'Machinedesign'), (4, 'Penalties')])),
            ],
        ),
        migrations.CreateModel(
            name='Scoresheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheetType', models.IntegerField(choices=[(1, 'Presentation'), (2, 'Journal'), (3, 'Machinedesign'), (4, 'Penalties')])),
                ('isSubmitted', models.BooleanField()),
                ('field1', models.FloatField(blank=True, null=True)),
                ('field2', models.FloatField(blank=True, null=True)),
                ('field3', models.FloatField(blank=True, null=True)),
                ('field4', models.FloatField(blank=True, null=True)),
                ('field5', models.FloatField(blank=True, null=True)),
                ('field6', models.FloatField(blank=True, null=True)),
                ('field7', models.FloatField(blank=True, null=True)),
                ('field8', models.FloatField(blank=True, null=True)),
                ('field9', models.FloatField(blank=True, null=True)),
                ('field10', models.FloatField(blank=True, null=True)),
                ('field11', models.FloatField(blank=True, null=True)),
                ('field12', models.FloatField(blank=True, null=True)),
                ('field13', models.FloatField(blank=True, null=True)),
                ('field14', models.FloatField(blank=True, null=True)),
                ('field15', models.FloatField(blank=True, null=True)),
                ('field16', models.FloatField(blank=True, null=True)),
                ('field17', models.FloatField(blank=True, null=True)),
                ('field18', models.FloatField(blank=True, null=True)),
                ('field19', models.FloatField(blank=True, null=True)),
                ('field20', models.FloatField(blank=True, null=True)),
                ('field21', models.FloatField(blank=True, null=True)),
                ('fieldText', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Penalties',
            new_name='MapContestToCluster',
        ),
        migrations.DeleteModel(
            name='JournalScores',
        ),
        migrations.DeleteModel(
            name='MachineDesignScores',
        ),
        migrations.DeleteModel(
            name='MapJudgeToJournalScores',
        ),
        migrations.DeleteModel(
            name='MapJudgeToMachineDesignScores',
        ),
        migrations.DeleteModel(
            name='MapJudgeToPresentationScores',
        ),
        migrations.DeleteModel(
            name='MapTeamToJournalScores',
        ),
        migrations.DeleteModel(
            name='MapTeamToMachineDesignScores',
        ),
        migrations.DeleteModel(
            name='MapTeamToPenalties',
        ),
        migrations.DeleteModel(
            name='MapTeamToPresentationScores',
        ),
        migrations.DeleteModel(
            name='PresentationScores',
        ),
        migrations.RenameField(
            model_name='mapcontesttocluster',
            old_name='MachinePenalties',
            new_name='clusterid',
        ),
        migrations.RenameField(
            model_name='mapcontesttocluster',
            old_name='PresentationPenalties',
            new_name='contestid',
        ),
        migrations.RenameField(
            model_name='mapcontesttojudge',
            old_name='judegeid',
            new_name='judgeid',
        ),
        migrations.RenameField(
            model_name='mapjudgetocluster',
            old_name='judegeid',
            new_name='judgeid',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='score_penalties',
            new_name='penalties_score',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='judge_cluster',
        ),
        migrations.AddField(
            model_name='contest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judge',
            name='phone_number',
            field=models.CharField(default=1111111, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='team_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='total_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
