# Generated by Django 4.2.16 on 2024-11-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoresheet',
            name='fieldText',
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field22',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field23',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='field9',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
