# Generated by Django 5.1.2 on 2024-10-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MapScoresheetToTeamJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.IntegerField()),
                ('judgeid', models.IntegerField()),
                ('scoresheetid', models.IntegerField()),
                ('sheetType', models.IntegerField(choices=[(1, 'Presentation'), (2, 'Journal'), (3, 'Machinedesign'), (4, 'Penalties')])),
            ],
        ),
        migrations.CreateModel(
            name='MapUserToCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField()),
                ('coachid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scoresheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheetType', models.IntegerField(choices=[(1, 'Presentation'), (2, 'Journal'), (3, 'Machinedesign'), (4, 'Penalties')])),
                ('isSubmitted', models.BooleanField()),
                ('field1', models.FloatField(blank=True, null=True)),
                ('field2', models.FloatField(blank=True, null=True)),
                ('field3', models.FloatField(blank=True, null=True)),
                ('field4', models.FloatField(blank=True, null=True)),
                ('field5', models.FloatField(blank=True, null=True)),
                ('field6', models.FloatField(blank=True, null=True)),
                ('field7', models.FloatField(blank=True, null=True)),
                ('field8', models.FloatField(blank=True, null=True)),
                ('field9', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Penalties',
            new_name='MapContestToCluster',
        ),
        migrations.RenameModel(
            old_name='MapJudgeToPresentationScores',
            new_name='MapUserToOrganizer',
        ),
        migrations.DeleteModel(
            name='JournalScores',
        ),
        migrations.DeleteModel(
            name='MachineDesignScores',
        ),
        migrations.DeleteModel(
            name='MapJudgeToJournalScores',
        ),
        migrations.DeleteModel(
            name='MapJudgeToMachineDesignScores',
        ),
        migrations.DeleteModel(
            name='MapTeamToJournalScores',
        ),
        migrations.DeleteModel(
            name='MapTeamToMachineDesignScores',
        ),
        migrations.DeleteModel(
            name='MapTeamToPenalties',
        ),
        migrations.DeleteModel(
            name='MapTeamToPresentationScores',
        ),
        migrations.DeleteModel(
            name='PresentationScores',
        ),
        migrations.RenameField(
            model_name='mapcontesttocluster',
            old_name='MachinePenalties',
            new_name='clusterid',
        ),
        migrations.RenameField(
            model_name='mapcontesttocluster',
            old_name='PresentationPenalties',
            new_name='contestid',
        ),
        migrations.RenameField(
            model_name='mapcontesttojudge',
            old_name='judegeid',
            new_name='judgeid',
        ),
        migrations.RenameField(
            model_name='mapjudgetocluster',
            old_name='judegeid',
            new_name='judgeid',
        ),
        migrations.RenameField(
            model_name='mapusertoorganizer',
            old_name='judgeid',
            new_name='organizerid',
        ),
        migrations.RenameField(
            model_name='mapusertoorganizer',
            old_name='scoresheetid',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='judge_cluster',
        ),
    ]
