# Generated by Django 5.1.1 on 2024-10-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emdcbackend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MapContestToCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contestid", models.IntegerField()),
                ("clusterid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MapScoresheetToTeamJudge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamid", models.IntegerField()),
                ("judgeid", models.IntegerField()),
                ("scoresheetid", models.IntegerField()),
                (
                    "sheetType",
                    models.IntegerField(
                        choices=[
                            (1, "Presentation"),
                            (2, "Journal"),
                            (3, "Machinedesign"),
                            (4, "Penalties"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scoresheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheetType",
                    models.IntegerField(
                        choices=[
                            (1, "Presentation"),
                            (2, "Journal"),
                            (3, "Machinedesign"),
                            (4, "Penalties"),
                        ]
                    ),
                ),
                ("isSubmitted", models.BooleanField()),
                ("field1", models.FloatField(blank=True, null=True)),
                ("field2", models.FloatField(blank=True, null=True)),
                ("field3", models.FloatField(blank=True, null=True)),
                ("field4", models.FloatField(blank=True, null=True)),
                ("field5", models.FloatField(blank=True, null=True)),
                ("field6", models.FloatField(blank=True, null=True)),
                ("field7", models.FloatField(blank=True, null=True)),
                ("field8", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(name="JournalScores",),
        migrations.DeleteModel(name="MachineDesignScores",),
        migrations.DeleteModel(name="MapJudgeToJournalScores",),
        migrations.DeleteModel(name="MapJudgeToMachineDesignScores",),
        migrations.DeleteModel(name="MapJudgeToPresentationScores",),
        migrations.DeleteModel(name="MapTeamToJournalScores",),
        migrations.DeleteModel(name="MapTeamToMachineDesignScores",),
        migrations.DeleteModel(name="MapTeamToPenalties",),
        migrations.DeleteModel(name="MapTeamToPresentationScores",),
        migrations.DeleteModel(name="Penalties",),
        migrations.DeleteModel(name="PresentationScores",),
        migrations.RenameField(
            model_name="mapcontesttojudge", old_name="judegeid", new_name="judgeid",
        ),
        migrations.RenameField(
            model_name="mapjudgetocluster", old_name="judegeid", new_name="judgeid",
        ),
        migrations.RemoveField(model_name="coach", name="school_name",),
        migrations.RemoveField(model_name="teams", name="judge_cluster",),
        migrations.AddField(
            model_name="organizer",
            name="region",
            field=models.CharField(default="region", max_length=50),
            preserve_default=False,
        ),
    ]
