# Generated by Django 5.1.1 on 2024-10-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emdcbackend", "0002_rename_teams_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapTeamToPenalties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamid", models.IntegerField()),
                ("scoresheetid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Penalties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PresentationPenalties", models.IntegerField()),
                ("MachinePenalties", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=99)),
                ("journal_score", models.FloatField()),
                ("presentation_score", models.FloatField()),
                ("machinedesign_score", models.FloatField()),
                ("score_penalties", models.FloatField()),
                ("judge_cluster", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="MapContestToRegion",),
        migrations.DeleteModel(name="Region",),
        migrations.DeleteModel(name="Team",),
        migrations.RenameField(
            model_name="mapcoachtoteam", old_name="uuid", new_name="coachid",
        ),
    ]
