# Generated by Django 4.2.16 on 2024-11-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0003_alter_judge_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_prelim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judge',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Lead'), (2, 'General'), (3, 'Technical'), (4, 'Journal')], null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='cluster_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
